[build]
  publish = "dist"
  command = "npm run build"

[dev]
  publish = "dist"
  command = "npm start"

[[redirects]]
  from = "/js/nalced.js"
  to = "https://plausible.io/js/plausible.js"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/not-found"
  status = 404
  Country=fr
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://plausible.io/api/event"
  status = 202
  force = true

[[redirects]]
  from = "/journal/week-notes/"
  to = "/week-notes/"
  status = 301
  force = true

[[redirects]]
  from = "/journal/:year/week-notes/*"
  to = "/week-notes/:year/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/latestTracks"
  to = "/functions/GetLatestTracks"
  status = 200
  force = true

[functions]
  directory = "functions"

[[redirects]]
  from = "/.well-known/webfinger"
  to = "https://indieweb.social/.well-known/webfinger?resource=acct:declan_byrd@indieweb.social"
  status = 200

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "dist/img", # Eleventy Image Disk Cache
    ".cache", # Remote Asset Cache
  ]